# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_id', models.BigIntegerField()),
                ('train_data_num', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('loss', models.FloatField()),
                ('train_start_time', models.DateTimeField()),
                ('train_cost_time', models.TimeField()),
            ],
            options={
                'db_table': 'model_history',
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(max_length=20, primary_key=True, serialize=False)),
                ('online_url', models.CharField(max_length=200)),
                ('offline_url', models.CharField(max_length=200)),
                ('is_online', models.SmallIntegerField()),
                ('is_training', models.SmallIntegerField()),
                ('app_id', models.BigIntegerField()),
                ('is_replace', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'model_info',
            },
        ),
    ]
